FROM node:22-alpine

WORKDIR /app

RUN apk update && apk add --no-cache ca-certificates

RUN apk add --no-cache curl

RUN corepack enable && corepack prepare pnpm@9 --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

ENV NODE_ENV=Development

EXPOSE 3009

CMD ["node_modules/.bin/nodemon", "index.js"]